packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  "@milaboratory/tengo-template-builder": ^1.10.0
  "@milaboratory/pl-block-tools": ^2.1.5
  "@milaboratory/block-builder": ^1.2.3

  "@milaboratory/sdk-ui": ^0.12.11
  "@milaboratory/sdk-test": ^1.4.3

  "@milaboratory/tengo-sdk": ^1.0.7

  "@milaboratory/platforma-uikit": ^1.0.14
  "@milaboratory/sdk-vue": ^1.0.23
  "@milaboratory/helpers": ^1.5.2

  "vue": ^3.4.37
  "vue-tsc": ^2.0.29

  "zod": ^3.23.8

  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.4.0
  "vitest": ^2.0.5
  "@vitejs/plugin-vue": ^5.1.2

  "@changesets/cli": ^2.27.7
