packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.24
  '@platforma-sdk/model': ^1.24.5
  '@platforma-sdk/ui-vue': ^1.24.5
  '@platforma-sdk/tengo-builder': ^2.0.1
  '@platforma-sdk/workflow-tengo': ^3.0.2

  '@platforma-sdk/test': ^1.24.7
  '@milaboratories/helpers': ^1.6.11

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'radashi': ^12.3.0
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.2.3
  'vitest': ^3.0.9
  '@vitejs/plugin-vue': ^5.2.3

  '@vueuse/core': ^12.2.0

  'ag-grid-enterprise': &ag-grid ^33.2.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.27.11

  '@types/node': ~20.16.15
