packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@milaboratory/tengo-template-builder': ^1.14.3
  '@milaboratory/pl-block-tools': ^2.1.5
  '@milaboratory/block-builder': ^1.2.3

  '@milaboratory/sdk-ui': ^0.12.22
  '@milaboratory/sdk-test': ^1.5.5

  '@milaboratory/tengo-sdk': ^1.2.2

  '@milaboratory/platforma-uikit': ^1.1.16
  '@milaboratory/sdk-vue': ^1.1.5
  '@milaboratory/helpers': ^1.6.0

  'vue': ^3.5.5
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ^5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.5
  'vitest': ^2.1.1
  '@vitejs/plugin-vue': ^5.1.3

  '@ag-grid-community/core': ^32.1.0
  '@ag-grid-community/client-side-row-model': ^32.1.0
  '@ag-grid-community/vue3': ^32.1.0
  '@ag-grid-community/styles': ^32.1.0
  '@ag-grid-enterprise/core': ^32.1.0
  '@ag-grid-enterprise/rich-select': ^32.1.0
  '@ag-grid-enterprise/menu': ^32.1.0
  '@ag-grid-enterprise/clipboard': '^32.1.0'
  '@ag-grid-enterprise/range-selection': '^32.1.0'

  '@changesets/cli': ^2.27.8
