packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.63
  '@platforma-sdk/model': ^1.39.0
  '@platforma-sdk/ui-vue': ^1.39.0
  '@platforma-sdk/tengo-builder': ^2.1.7
  '@platforma-sdk/workflow-tengo': ^4.9.2
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-sdk/test': ^1.29.17
  '@milaboratories/helpers': ^1.6.11

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'radashi': ^12.3.0
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.6
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@vueuse/core': ^12.2.0

  'ag-grid-enterprise': &ag-grid ^33.2.1
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.27.11

  '@types/node': ~20.16.15
