packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@milaboratory/tengo-template-builder': ^1.13.0
  '@milaboratory/pl-block-tools': ^2.1.5
  '@milaboratory/block-builder': ^1.2.3

  '@milaboratory/sdk-ui': ^0.12.21
  '@milaboratory/sdk-test': ^1.5.5

  '@milaboratory/tengo-sdk': ~1.1.8

  '@milaboratory/platforma-uikit': ^1.1.2
  '@milaboratory/sdk-vue': ^1.1.1
  '@milaboratory/helpers': ^1.5.3

  'vue': ^3.4.38
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ^5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.3
  'vitest': ^2.0.5
  '@vitejs/plugin-vue': ^5.1.3

  '@ag-grid-community/core': ^32.1.0
  '@ag-grid-community/client-side-row-model': ^32.1.0
  '@ag-grid-community/vue3': ^32.1.0
  '@ag-grid-community/styles': ^32.1.0

  '@changesets/cli': ^2.27.8
