packages:
  - workflow
  - model
  - ui
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.14.13
  '@platforma-sdk/block-tools': ^2.3.10

  '@platforma-sdk/model': ^1.2.32
  '@platforma-sdk/test': ^1.5.37

  '@platforma-sdk/workflow-tengo': ^1.2.11

  '@platforma-sdk/ui-vue': ^1.4.9
  '@milaboratories/helpers': ^1.6.5

  'vue': ^3.5.11
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.1.3

  'vite': ^5.4.8
  'vitest': ^2.1.2
  '@vitejs/plugin-vue': ^5.1.4

  '@ag-grid-community/core': ^32.2.2
  '@ag-grid-community/client-side-row-model': ^32.2.2
  '@ag-grid-community/vue3': ^32.2.2
  '@ag-grid-community/styles': ^32.2.2
  '@ag-grid-enterprise/core': ^32.2.2
  '@ag-grid-enterprise/rich-select': ^32.2.2
  '@ag-grid-enterprise/menu': ^32.2.2
  '@ag-grid-enterprise/clipboard': ^32.2.2
  '@ag-grid-enterprise/range-selection': ^32.2.2

  '@changesets/cli': ^2.27.9
