packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.14.11
  '@platforma-sdk/block-tools': ^2.2.0

  '@platforma-sdk/model': ^1.2.26
  '@platforma-sdk/test': ^1.5.16

  '@platforma-sdk/workflow-tengo': ^1.2.8

  '@milaboratories/uikit': ^1.2.4
  '@platforma-sdk/ui-vue': ^1.3.7
  '@milaboratories/helpers': ^1.6.2

  'vue': ^3.5.5
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2

  'vite': ^5.4.8
  'vitest': ^2.1.1
  '@vitejs/plugin-vue': ^5.1.4

  '@ag-grid-community/core': ^32.2.1
  '@ag-grid-community/client-side-row-model': ^32.2.1
  '@ag-grid-community/vue3': ^32.2.1
  '@ag-grid-community/styles': ^32.2.1
  '@ag-grid-enterprise/core': ^32.2.1
  '@ag-grid-enterprise/rich-select': ^32.2.1
  '@ag-grid-enterprise/menu': ^32.2.1
  '@ag-grid-enterprise/clipboard': ^32.2.1
  '@ag-grid-enterprise/range-selection': ^32.2.1

  '@changesets/cli': ^2.27.8
