packages:
  - software/parse-h5ad
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.6.7
  '@platforma-sdk/model': ^1.43.14
  '@platforma-sdk/ui-vue': ^1.43.14
  '@platforma-sdk/tengo-builder': ^2.2.0
  '@platforma-sdk/workflow-tengo': ^5.2.3
  '@platforma-sdk/package-builder': ^3.8.0
  "@platforma-sdk/blocks-deps-updater": ^2.0.0
  "@platforma-sdk/eslint-config": ^1.1.0

  '@platforma-sdk/test': ^1.43.15
  '@milaboratories/helpers': ^1.9.0

  '@platforma-open/milaboratories.runenv-python-3': ^1.4.13

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'radashi': ^12.3.0
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.6
  'vitest': ^2.1.9
  '@vitejs/plugin-vue': ^5.2.1
  'vite-plugin-dts': ^4.3.0

  '@vueuse/core': ^12.2.0

  'ag-grid-enterprise': &ag-grid ^34.1.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.27.11

  '@types/node': ~20.16.15
