packages:
  - block
  - model
  - software/parse-h5ad
  - software/parse-seurat
  - test
  - ui
  - workflow

catalog:
  "@platforma-sdk/block-tools": 2.11.2
  "@platforma-sdk/model": 1.79.17
  "@platforma-sdk/ui-vue": 1.79.17
  "@platforma-sdk/tengo-builder": 4.0.9
  "@platforma-sdk/workflow-tengo": 6.6.5
  "@platforma-sdk/blocks-deps-updater": 2.2.0
  "@platforma-sdk/package-builder": 3.13.0

  "@platforma-open/milaboratories.runenv-python-3": ^1.7.5
  "@platforma-open/milaboratories.runenv-r-samples-and-data": ^1.0.1

  "@platforma-sdk/test": 1.79.18
  "@milaboratories/helpers": 1.14.1
  "@milaboratories/pl-model-common": ^1.31.2

  "vue": 3.5.24

  "zod": ~3.25.76
  "radashi": ^12.7.0
  "utility-types": ^3.11.0

  "typescript": ~5.6.3
  "turbo": ^2.6.1

  "vitest": ^4.0.10
  "shx": ^0.4.0

  "@vueuse/core": ^12.2.0

  "ag-grid-enterprise": &ag-grid ~34.1.2
  "ag-grid-vue3": *ag-grid

  "@changesets/cli": ^2.29.7

  "@types/node": ~20.16.15
  "@milaboratories/ts-builder": 1.5.2
  "@milaboratories/ts-configs": 1.2.3
