packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.0
  '@platforma-sdk/model': ^1.14.1
  '@platforma-sdk/ui-vue': ^1.14.20
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/workflow-tengo': ^2.6.0

  '@platforma-sdk/test': ^1.14.10
  '@milaboratories/helpers': ^1.6.8

  'vue': ^3.5.13
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.3.3

  'vite': ^6.0.2
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@vueuse/core': ^12.0.0

  '@ag-grid-community/core': &ag-grid ^32.3.3
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid
  '@ag-grid-enterprise/core': *ag-grid
  '@ag-grid-enterprise/rich-select': *ag-grid
  '@ag-grid-enterprise/menu': *ag-grid
  '@ag-grid-enterprise/clipboard': *ag-grid
  '@ag-grid-enterprise/range-selection': *ag-grid

  '@changesets/cli': ^2.27.10

  '@types/node': ~20.16.15
