packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.6.2
  '@platforma-sdk/model': ^1.42.51
  '@platforma-sdk/ui-vue': ^1.42.51
  '@platforma-sdk/tengo-builder': ^2.1.18
  '@platforma-sdk/workflow-tengo': ^5.1.4
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@platforma-sdk/test': ^1.42.52
  '@milaboratories/helpers': ^1.7.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'radashi': ^12.3.0
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.0.6
  'vitest': ^2.1.9
  '@vitejs/plugin-vue': ^5.2.1
  'vite-plugin-dts': ^4.3.0

  '@vueuse/core': ^12.2.0

  'ag-grid-enterprise': &ag-grid ^34.1.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.27.11

  '@types/node': ~20.16.15
