packages:
  - workflow
  - model
  - ui
  - test
  - .

catalog:
  '@platforma-sdk/block-tools': ^2.3.21
  '@platforma-sdk/model': ^1.7.20
  '@platforma-sdk/ui-vue': ^1.7.37
  '@platforma-sdk/tengo-builder': ^1.16.1
  '@platforma-sdk/workflow-tengo': ^1.7.2

  '@platforma-sdk/test': ^1.7.38
  '@milaboratories/helpers': ^1.6.6

  'vue': ^3.5.12
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.2.3

  'vite': ^5.4.10
  'vitest': ^2.1.4
  '@vitejs/plugin-vue': ^5.1.4

  '@vueuse/core': ^11.2.0

  '@ag-grid-community/core': &ag-grid ^32.3.2
  '@ag-grid-community/client-side-row-model': *ag-grid
  '@ag-grid-community/vue3': *ag-grid
  '@ag-grid-community/styles': *ag-grid
  '@ag-grid-enterprise/core': *ag-grid
  '@ag-grid-enterprise/rich-select': *ag-grid
  '@ag-grid-enterprise/menu': *ag-grid
  '@ag-grid-enterprise/clipboard': *ag-grid
  '@ag-grid-enterprise/range-selection': *ag-grid

  '@changesets/cli': ^2.27.9

  '@types/node': ~20.16.15
