packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.0
  '@platforma-sdk/model': ^1.20.11
  '@platforma-sdk/ui-vue': ^1.20.21
  '@platforma-sdk/tengo-builder': ^1.17.4
  '@platforma-sdk/workflow-tengo': ^2.8.4

  '@platforma-sdk/test': ^1.14.10
  '@milaboratories/helpers': ^1.6.11

  'vue': ^3.5.13
  'vue-tsc': ^2.1.6

  'zod': ^3.23.8
  'utility-types': ^3.11.0

  'typescript': ~5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.3.3

  'vite': ^6.0.2
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@vueuse/core': ^12.0.0

  'ag-grid-enterprise': &ag-grid ^33.0.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.27.10

  '@types/node': ~20.16.15
