packages:
  - software/parse-h5ad
  - software/parse-seurat
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': 2.6.22
  '@platforma-sdk/model': 1.45.35
  '@platforma-sdk/ui-vue': 1.45.35
  '@platforma-sdk/tengo-builder': 2.3.10
  '@platforma-sdk/workflow-tengo': ^5.6.2
  "@platforma-sdk/blocks-deps-updater": 2.0.0
  "@platforma-sdk/eslint-config": ^1.1.0
  '@platforma-sdk/package-builder': 3.10.7

  '@platforma-open/milaboratories.runenv-python-3': ^1.6.2
  '@platforma-open/milaboratories.runenv-r-samples-and-data': ^1.0.1

  '@platforma-sdk/test': 1.45.35
  '@milaboratories/helpers': 1.12.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ~3.23.8
  'radashi': ^12.7.0
  'utility-types': ^3.11.0

  'typescript': ~5.6.3
  'tsup': ~8.4.0
  'turbo': ^2.6.1

  'vite': ^6.0.6
  'vitest': ^4.0.10
  '@vitejs/plugin-vue': ^5.2.1
  'vite-plugin-dts': ^4.3.0

  '@vueuse/core': ^12.2.0

  'ag-grid-enterprise': &ag-grid ^34.1.2
  'ag-grid-vue3': *ag-grid

  '@changesets/cli': ^2.29.7

  '@types/node': ~20.16.15
