name: Build and Test NPM packages
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init

    uses: milaboratory/github-ci-internal/.github/workflows/node-docker-simple-fast-pnpm.yaml@v4
    with:
      app-name: Samples & Data
      app-name-slug: 'block-samples-and-data'
      notify-telegram: true

      node-version: '20.x'
      always-auth: 'true'

      build-script-name: 'build'
      
      test: true
      test-script-name: 'test'


    secrets:
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
