name: Build, Test & Publish Block
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch: {}
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4
        with:
          version-canonize: false
          branch-versioning: main
  run:
    needs:
      - init
    uses: milaboratory/github-ci/.github/workflows/node-docker-simple-fast-pnpm.yaml@v4-beta
    with:
      app-name: Samples & Data
      app-name-slug: 'samples-and-data'
      notify-telegram: true
      node-version: '20.x'
      build-script-name: 'build'
      test: true
      test-script-name: 'test'
      pnpm-recursive-build: true
      pnpm-recursive-tests: true
      publish-to-public: 'false'
      npmrc-config: |
        {
          "registries": {
            "https://npm.pkg.github.com/": {
              "scopes": ["platforma-open"],
              "tokenVar": "NODE_AUTH_TOKEN"
            }
          }
        }
    secrets:
      env: |
        {
          "PL_LICENSE": ${{ toJSON(secrets.MI_LICENSE) }},
          "MI_LICENSE": ${{ toJSON(secrets.MI_LICENSE) }},
          "PL_CI_TEST_USER": ${{ toJSON(secrets.PL_CI_TEST_USER) }},
          "PL_CI_TEST_PASSWORD": ${{ toJSON(secrets.PL_CI_TEST_PASSWORD) }},
          "AWS_CI_IAM_MONOREPO_SIMPLE_ROLE": ${{ toJSON(secrets.AWS_CI_IAM_MONOREPO_SIMPLE_ROLE) }}
        }
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
